### ISSUE TITLE
--fix not working

### ISSUE THREAD

**Issue by theunreal** [ionic-team/v4-migration-tslint#78]
I'm trying to run the following command:

```
npx tslint -c ionic-migration.json -p tsconfig.json --fix
```

The linter does not fix anything, just outputs the same as it did without the --fix flag. 
a lot of errors/warnings like this:

```
ERROR: (ion-overlay-method-present-should-use-await) C:/xampp/htdoc
s/ioniconfe2/src/app/members/chat-window/chat-window.ts[103, 17]: T
he present method of overlay controllers now returns a promise.
Please ensure that you are handling this promise correctly.
```

I'm missing something?

**Comment by dwieeb** [comment]
@theunreal Some rules cannot be automatically fixed because it would either be unsafe or we need human input. 

The list of fixable rules is identified via a wrench (🔧) in the rules table: https://github.com/ionic-team/v4-migration-tslint#rules

If you believe a rule should be fixable, please make a case. This particular rule, and others like it, is not "fixable" because a once synchronous workflow is now asynchronous in Ionic 4. The handling of that migration should involve human input, as it is ad hoc and very complicated in some cases.
